### ISSUE TITLE
Model run error for transit route system with rail lines

### ISSUE THREAD

**Issue by heejham33** [OahuMPO/OahuTDFM#61]
The OahuMPO TDFM officially released on Dec 1, 2023 encountered an error when the transit route system included the rail routes as transit mode# 7. The error happened while performing the "Filter Rail Utility Spec" macro inside "JointTours Mode Eval" macro. The error message was "Please specify the model alternatives.". We tested both input master transit route system and scenario network provided by Kyle, but both runs generated the same error message.

**Comment by dkyleward** [comment]
Fixed. I will create a v1.0.1 hotfix release with this change and get it to you shortly.
